Models created.
SheCodesAus/2024_bit_by_bit_back_end pull request #1
Opened 2024-03-20 01:23 UTC by COHally

## Describe your changes
Models created for Django back end. 
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## What kind of feedback do you need?
Models/database schema have already been discussed at length to a quick look will be sufficient. 
## Checklist:
- [x] I have performed a self-review of my code
- [x] I have recommended where to start and how to proceed with the review

2024-03-20 01:28 UTC, caoimhejyoti approved these changes
Looking brilliant. Nice work getting this smashed out!

2024-03-21 00:57 UTC, caoimhejyoti requested changes
Looking great Cathy - just a couple of things that I have spotted.

2024-03-21 00:57 UTC, caoimhejyoti commented on byte_time/events/models.py
Damn! how did we miss this!

2024-03-21 00:57 UTC, caoimhejyoti commented on byte_time/events/views.py
I don't think that the createEvent class is correct. Referring to my previous back end, I had a Festival list which included a get an post. I then had a detailed list which had the get, put and delete.

2024-03-21 00:57 UTC, caoimhejyoti commented on byte_time/events/views.py
Your delete references pledge - possibly pulled from previous project?

Also the comment "#Update Projects" on line 49 is possible the same.

2024-03-21 10:10 UTC, caoimhejyoti requested changes
see comment re:event mentor/mentor table loop.

2024-03-21 10:10 UTC, caoimhejyoti commented on byte_time/events/models.py
There is a possible loop between the event mentor and the event table - can we just talk that through this possible loop and confirm?

2024-03-21 11:51 UTC, COHally commented on byte_time/events/models.py
Yes, of course.

2024-03-21 12:34 UTC, caoimhejyoti approved these changes
NAILED IT!

2024-03-21 14:27 UTC, Jigudhari approved these changes
Great Job Cathy!!

2024-03-21 22:30 UTC, merged